version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    privileged: true
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - path: ./.env
        required: true
      - path: ./.env.local
        required: true
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - $PWD/postgres/config:/etc/postgresql:ro
      - $PWD/postgres/init:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:rw
    environment:
      REDIS_REPLICATION_MODE: master
      REDISCLI_AUTH: ${REDIS_PASSWORD}
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
