service: app

frameworkVersion: '3'	
useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  memorySize: 128
  environment:
    LOG_LEVEL: INFO
    REGION: ${self.provider.region}
    SECRET_KEY: ${env:SECRET_KEY}
    POSTGRES_USER: ${env:POSTGRES_USER}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    POSTGRES_PORT: ${env:POSTGRES_PORT}
    POSTGRES_DATABASE: ${env:POSTGRES_DATABASE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: "*"

plugins:
  - serverless-python-requirements
  - serverless-localstack

custom:
  localstack:
    stages:
      - local

functions:
  api:
    handler: main.handler
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'
