service: person

frameworkVersion: '3'	
useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  memorySize: 128
  environment:
    LOG_LEVEL: INFO
    REGION: ${self.provider.region}
    SECRET_KEY: ${ssm:kms-api-key}
    POSTGRES_USER: ${env:POSTGRES_USER}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    POSTGRES_PORT: ${env:POSTGRES_PORT}
    POSTGRES_DATABASE: ${env:POSTGRES_DATABASE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: "*"

plugins:
  - serverless-python-requirements
  - serverless-localstack

custom:
  pythonRequirements:
    usePipenv: false
  localstack:
    stages:
      - local

functions:
  api:
    handler: person.handler
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'

resources:
  Resources:
    APIKey:
      Type: AWS::KMS::Key
      Properties:
        Description: "KMS API Key"
        KeyPolicy:
          Version: "2012-10-17"
          Id: "kms-api-key"
          Statement:
            - Sid: "Allow access to API"
              Effect: "Allow"
              Principal:
                AWS: "arn:aws:iam::000000000000:user/admin"
              Action:
                - "kms:*"
              Resource: "*"
    APIKeyAlias:
      Type: AWS::KMS::Alias
      Properties:
        AliasName: "alias/person-kms-api-key"
        TargetKeyId: !Ref APIKey
